# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z007sclg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/hdl/MicroBlaze_wrapper.v}}
add_files {{C:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/MicroBlaze.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0_ooc_debug.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_dlmb_v10_0/MicroBlaze_dlmb_v10_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_dlmb_v10_0/MicroBlaze_dlmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_ilmb_v10_0/MicroBlaze_ilmb_v10_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_ilmb_v10_0/MicroBlaze_ilmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_dlmb_bram_if_cntlr_0/MicroBlaze_dlmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_ilmb_bram_if_cntlr_0/MicroBlaze_ilmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_lmb_bram_0/MicroBlaze_lmb_bram_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0_ooc_trace.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_mdm_1_0/MicroBlaze_mdm_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_clk_wiz_1_0/MicroBlaze_clk_wiz_1_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_clk_wiz_1_0/MicroBlaze_clk_wiz_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_clk_wiz_1_0/MicroBlaze_clk_wiz_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_1_100M_0/MicroBlaze_rst_clk_wiz_1_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_1_100M_0/MicroBlaze_rst_clk_wiz_1_100M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_rst_clk_wiz_1_100M_0/MicroBlaze_rst_clk_wiz_1_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_processing_system7_0_0/MicroBlaze_processing_system7_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/MicroBlaze_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/data/mb_bootloop_le.elf}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Rintaro Sanada/Downloads/XilinxFPGA_SE/Zybo_Z7-10/dai6sho/blink_ip_mb/blink_ip_mb.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Rintaro Sanada/Downloads/XilinxFPGA_SE/Zybo_Z7-10/dai6sho/blink_ip_mb/blink_ip_mb.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MicroBlaze_wrapper -part xc7z007sclg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MicroBlaze_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MicroBlaze_wrapper_utilization_synth.rpt -pb MicroBlaze_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
