# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0.xci
# IP: The module: 'MicroBlaze_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0.xci
# IP: The module: 'MicroBlaze_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rintaro Sanada/verilog/MicroBlaze/MicroBlaze.srcs/sources_1/bd/MicroBlaze/ip/MicroBlaze_microblaze_0_0/MicroBlaze_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
